stages:
  - test
  - build
  - sign

variables:
  REGISTRY: $GITLAB_REGISTRY/$CI_PROJECT_PATH

client-tests:
  stage: test
  image: node:18-alpine
  script:
    - cd todo-client
    - npm i
    - npm run test
  only:
    - main

api-tests:
  stage: test
  image: maven:3.9-eclipse-temurin-17
  script:
    - cd todo-api
    - ./mvnw test
  only:
    - main

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker build -f todo-client/Containerfile -t "$REGISTRY/todo-client:latest" todo-client
    - docker build -f todo-api/Containerfile -t "$REGISTRY/todo-api:latest" todo-api
    - docker push "$REGISTRY/todo-client:latest"
    - docker push "$REGISTRY/todo-api:latest"
  only:
    - main

sign:
  stage: sign
  image: alpine:3.19
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_TLS_CERTDIR: ""
    REGISTRY: $CI_REGISTRY/$CI_PROJECT_PATH
  before_script:
    - apk add --no-cache curl docker
    - curl -sSLO https://github.com/sigstore/cosign/releases/download/v2.2.0/cosign-linux-amd64
    - install -m 755 cosign-linux-amd64 /usr/local/bin/cosign
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - echo "Signing todo-client..."
    - COSIGN_PASSWORD="" cosign sign --key cosign/cosign.key -y "$REGISTRY/todo-client:latest"
    
    - echo "Signing todo-api..."
    - COSIGN_PASSWORD="" cosign sign --key cosign/cosign.key -y "$REGISTRY/todo-api:latest"

    - echo "Verifying todo-client signature..."
    - cosign verify --key cosign/cosign.pub "$REGISTRY/todo-client:latest" || (echo "Verification failed for todo-client" && exit 1)

    - echo "Verifying todo-api signature..."
    - cosign verify --key cosign/cosign.pub "$REGISTRY/todo-api:latest" || (echo "Verification failed for todo-api" && exit 1)
  artifacts:
    paths:
      - cosign/cosign.pub
  dependencies:
    - build
  only:
    - main
