{{- if .Values.gitlab.token }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gitlab.imagePullSecret }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" .Values.gitlab.registry .Values.gitlab.username .Values.gitlab.token .Values.gitlab.email (printf "%s:%s" .Values.gitlab.username .Values.gitlab.token | b64enc) | b64enc }}
{{- end }}
