apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      initContainers:
        - name: verify-image
          image: gcr.io/projectsigstore/cosign:v2.2.0
          command: ["cosign", "verify", "--key=/cosign/cosign.pub", "{{ .Values.gitlab.registry }}/{{ .Values.gitlab.group }}/{{ .Values.gitlab.project }}/todo-api:latest"]
          volumeMounts:
            - name: cosign-key
              mountPath: /cosign
      containers:
        - name: todo-api
          image: {{ .Values.gitlab.registry }}/{{ .Values.gitlab.group }}/{{ .Values.gitlab.project }}/todo-api:latest
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/todo
            - name: SPRING_DATASOURCE_USERNAME
              value: todo
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-password
                  key: POSTGRES_PASSWORD
            - name: SPRING_DATASOURCE_DRIVER_CLASS_NAME
              value: org.postgresql.Driver
            - name: SPRING_JPA_DATABASE_PLATFORM
              value: org.hibernate.dialect.PostgreSQLDialect
          ports:
            - containerPort: 8080
      volumes:
        - name: cosign-key
          configMap:
            name: cosign-public-key
---
apiVersion: v1
kind: Service
metadata:
  name: todo-api
spec:
  selector:
    app: todo-api
  ports:
    - port: 8080
